updated homeseer install script, and supporting files

diff --git a/overlay/etc/cont-init.d/10-homeseer-install b/overlay/etc/cont-init.d/10-homeseer-install
--- a/overlay/etc/cont-init.d/10-homeseer-install
+++ b/overlay/etc/cont-init.d/10-homeseer-install
@@ -1,16 +1,12 @@
-#!/usr/bin/with-contenv sh
-
+#!/usr/bin/with-contenv bash
+HS_VERSION_FILE=$HS_HOME/container_version.txt
 # Install HomeSeer if container is started for the first time
-if [ -e /DO_INSTALL ]
-
-then
-    echo "HomeSeer (re)install/update required at container first run. Installing at /opt/HomeSeer..."
-
-    wget -O /tmp/homeseer.tgz "http://homeseer.com/updates4/linux_$HOMESEER_VERSION.tar.gz"
-    tar -xzo -C /opt/ -f /tmp/homeseer.tgz
-    rm -f /tmp/*
-    rm -f /DO_INSTALL
-
+if ! grep -Fxq "${HOMESEER_VERSION}" $HS_VERSION_FILE ;  then
+  echo "HomeSeer (re)install/update required at container first run. Installing at /opt/HomeSeer..."
+  wget -O /tmp/homeseer.tgz "https://homeseer.com/updates4/linux_$HOMESEER_VERSION.tar.gz"
+  tar -xzo -C $HS_HOME -f /tmp/homeseer.tgz --strip-components=1
+  echo "${HOMESEER_VERSION}" > $HS_VERSION_FILE
+  rm -f /tmp/*
 else
     echo "HomeSeer already installed, not (re)installing/updating..."
 
